%YAML:1.0
# SPDX-FileCopyrightText: Copyright (c) 2018-2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: MIT
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.

BaseConfig:
  minDetectorConfidence: 0.22943838218073478
TargetManagement:
  preserveStreamUpdateOrder: 0
  maxTargetsPerStream: 400
  earlyTerminationAge: 1
  outputTerminatedTracks: 1
  enableBboxUnClipping: 0
  maxShadowTrackingAge: 64
  minIouDiff4NewTarget: 0.6329505083285663
  minTrackerConfidence: 0.8334914241970038
  probationAge: 9
TrajectoryManagement:
  useUniqueID: 0
  enableReAssoc: 1
  prepLength4TrajectoryProjection: 53
  maxTrackletMatchingTimeSearchRange: 24
  trajectoryProjectionProcessNoiseScale: 0.01
  trajectoryProjectionMeasurementNoiseScale: 100
  trackletSpacialSearchRegionScale: 0.01
  matchingScoreWeight4ReidSimilarity: 0.08016706183512573
  matchingScoreWeight4TrackletSimilarity: 0.06137868158082205
  maxAngle4TrackletMatching: 109
  minBboxSizeSimilarity4TrackletMatching: 0.1821974497006853
  minMatchingScore4Overall: 0.01802658341187635
  minMatchingScore4ReidSimilarity: 0.46370889173816704
  minSpeedSimilarity4TrackletMatching: 0.06750482824802526
  minTrackletMatchingScore: 0.1196452468278986
  minTrajectoryLength4Projection: 34
  reidExtractionInterval: 0
  trajectoryProjectionLength: 48
DataAssociator:
  dataAssociatorType: 0
  associationMatcherType: 1
  checkClassMatch: 1
  matchingScoreWeight4Iou: 0.8512052426782479
  matchingScoreWeight4SizeSimilarity: 0.19347499479023889
  matchingScoreWeight4VisualSimilarity: 0.0744031550731008
  minMatchingScore4Iou: 0.453411475027372
  minMatchingScore4Overall: 0.5410975203413544
  minMatchingScore4SizeSimilarity: 0.5135926884585114
  minMatchingScore4TentativeIou: 0.5557388537822727
  minMatchingScore4VisualSimilarity: 0.3154682906751356
  tentativeDetectorConfidence: 0.7484959375011256
StateEstimator:
  stateEstimatorType: 1
  measurementNoiseVar4Detector: 100.00000497224985
  measurementNoiseVar4Tracker: 7573.8827545885215
  processNoiseVar4Loc: 1057.948103348378
  processNoiseVar4Size: 7855.69455426151
  processNoiseVar4Vel: 3775.7408269598554
VisualTracker:
  visualTrackerType: 1
  useColorNames: 1
  useHog: 1
  featureImgSizeLevel: 3
  featureFocusOffsetFactor_y: -0.15655361993986983
  filterChannelWeightsLr: 0.010651706460556347
  filterLr: 0.014704404179973013
  gaussianSigma: 1.0384635863715812
ReID:
  reidType: 2
  outputReidTensor: 1
  batchSize: 100
  workspaceSize: 1000
  reidFeatureSize: 256
  reidHistorySize: 100
  inferDims: [3, 256, 128]
  networkMode: 1
  inputOrder: 0
  colorFormat: 0
  offsets: [127.5, 127.5, 127.5]
  netScaleFactor: 0.007843137254902
  keepAspc: 1
  addFeatureNormalization: 1
  tltModelKey: nvidia_tao
  onnxFile: models/mtmc/swin_tiny_tao.onnx
  modelEngineFile: models/mtmc/swin_tiny_tao.onnx_b100_gpu0_fp16.engine
